language: python
python:
  - "2.7.10"
install:
    - pip install -r backend/requirements.txt
    - npm install jshint
#    - npm install && bower install
before_script:
    - flake8 backend/
    - jshint frontend/app/
script:
    - python backend/manage.py test
